<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworks-WPF)</TargetFrameworks>
    <OutputType>library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\FINE.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="log4net" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.WPF" />
    <PackageReference Include="Splat" />
    <PackageReference Include="Splat.Builder" />
    <PackageReference Include="Splat.Core" />
    <PackageReference Include="Splat.Logging" />
    <PackageReference Include="Splat.Drawing" />
  </ItemGroup>
</Project>
