<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworks-WPF)</TargetFrameworks>
    <OutputType>Library</OutputType>
    <RootNamespace>FINE.Toolkit</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\FINEToolkit.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FINE.WPF\FINE.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="23.2.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Group\AddEndpointDropPanel\AddEndpointDropPanelView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Page Update="Group\AddEndpointDropPanel\AddEndpointDropPanelView.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
</Project>
