<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworks-WPF)</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <StartupObject>ExampleCodeGenApp.App</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\grid.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\grid.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FINEToolkit.WPF\FINEToolkit.WPF.csproj" />
    <ProjectReference Include="..\FINE.WPF\FINE.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" />
    <PackageReference Include="MoonSharp" />
    <PackageReference Include="ReactiveUI" />
  </ItemGroup>
</Project>
